### PR TITLE
Settings ui

### PR DESCRIPTION
**Pull request by jorgerobles**
Added QuadrantField to select image alignment options
Some minor layout fixing (added scroll-y to sidebar -- some settings were never reachable)

### CODE REVIEW

**Comment by jorgerobles** [comment]
@openhardwarecoza @tbfleming Following settings UI, we need to implement some form validation rules, but currently the fields are bound to the state **onChange**. Should We do the submit form pattern or maybe prevent operations elsewhere if there are missing parameters? The former is the classic way, the later could be better if you are just dabbling around and don't want to get nagged with the settings form.

Some questions:

1. On some MVC, the validation is bound to the Model, some others to the Action. What do you prefer? I its Model bound, I would bet the reducer to place beforeSave validation. Is it correct?
2. Should we prepare the settings to be sent to a server backend, or simply put on LocalStorage?

**Comment by jorgerobles** [comment]
Maybe this will help? http://redux-form.com/6.1.0/

**Comment by jorgerobles** [comment]
I've got something funcional, I will push in a couple of hours. It uses
local state of the component, but It's elegant 😜

**Comment by tbfleming** [comment]
Local state is fine as long as it doesn't cause problems when it goes missing. Hot reloading discards the old component tree and constructs a new one with new state. Only the store survives.

**Comment by jorgerobles** [comment]
Hi, I've pushed to settings-ui branch of my repo. BTW, What tool do you use to make screencaps?

**Comment by tbfleming** [comment]
screen2gif

**Comment by jorgerobles** [comment]
Ta-da!

validation

**Comment by tbfleming** [comment]
That may be just a CSS change away from a popup balloon :)

**Comment by jorgerobles** [comment]
@tbfleming  there's a little issue with balloons on CAM page. They have fixed position so get on place if you have scroll due several operations. I will try to patch if does not interfere with your work.

May We unify the form input libraries so can be reused on the several sections? As using https://react-bootstrap.github.io/ , It comes with several common components as tooltips or collapses. What do you think?

**Comment by tbfleming** [comment]
@jorgerobles go ahead and fix the balloons. I suspect they'll need code which tracks the scrollbar position.

Bootstrap looks nice, which is why it's on the Settings page, but it eats up too much space for the CAM page. The CAM page's form components don't have much that can be reused; they have minimal styling and deal mainly with CAM-specific stuff: error detection, the vertical blue selection indicator, and the CAM's unique way of field handling that responds to the selected operation type.

**Comment by jorgerobles** [comment]
@tbfleming here are the balloons. They are not fixed as yours, but have enough cues for error checking. Using react-bootstrap, not commited yet. Also I've got compact style for forms.

new_style

**Comment by openhardwarecoza** [comment]
Looks great!

**Comment by tbfleming** [comment]
Is there a way to keep the error balloons up?

**Comment by jorgerobles** [comment]
Not quite :| .  The first time the error balloon is shown up, but I have
been trying to keep them shown but interferes with the scroll issue.

**Comment by tbfleming** [comment]
Is there a way to disable or speed up Bootstrap's animations? Slow fades and slow collapse/expand make things feel sluggish to me. I started pulling my hair out on websites which do that a couple years ago. Fortunately most websites I visit dropped that fad. I think they also dropped Bootstrap :(

**Comment by jorgerobles** [comment]
Hmm, most of them are css transitions. I will investigate.

**Comment by jorgerobles** [comment]
http://stackoverflow.com/questions/13119912/disable-bootstraps-collapse-open-close-animation.
;)

**Comment by tbfleming** [comment]
I suspect that keeping them up will require a little bit of scripting that reacts to the scroll.
* Hard way: rip into bootstrap's guts
* Easier way: create a new React component with CSS similar to what I created

**Comment by jorgerobles** [comment]
I've spent several hours doing the hard way, and I've found there's indeed a https://react-bootstrap.github.io/react-overlays/#position that should do what you want. 
But I've got no success implementing due some "Stateless Component refs error" babble. I'm sure you could dig down the error on a blink :)

**Comment by tbfleming** [comment]
There are two common types of components.

Functional Components (sometimes called stateless):
```
function Welcome(props) {
  return <h1>Hello, {props.name}</h1>;
}
```

Class Components:
```
class Welcome extends React.Component {
  render() {
    return <h1>Hello, {this.props.name}</h1>;
  }
}
```

Class components may have state and may use ```ref```; functional components can't do either.

Examples are from https://facebook.github.io/react/docs/components-and-props.html .

**Comment by tbfleming** [comment]
react-bootstrap's ```position``` is a good find; it will eventually do what we want. Right now though it's buggy (react-bootstrap is still under heavy development).

position

**Comment by tbfleming** [comment]
There were several complications which made it not so easy, e.g. clipping the errors for operations scrolled out of view. It now works:

error bubbles

**Comment by jorgerobles** [comment]
Wow! I bow before you, Sir! I will take a look right now.

**Comment by funinthefalls** [comment]
I can't wait until LW4 is ready for primetime....so many cool features.

**Pull request merged**
